language: android
jdk: oraclejdk8

sudo: false

env:
  global:
    - ANDROID_API_LEVEL = 29
    - ANDROID_BUILD_TOOLS_VERSION = 29.0.3
    - ANDROID_ABI = armeabi-v7a

before_install:
  - yes | sdkmanager "build-tools;29.0.3"
  - yes | sdkmanager "platforms;android-29"

android:
  components:
    - tools
    - build-tools
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean test jacocoFullReport coverallsJacoco