codecov:
  require_ci_to_pass: yes

coverage:
    status:
      project:
        default:
          target: auto
          threshold: 0%
          if_not_found: success
          if_ci_failed: error
          informational: false
          only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no